name: check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno fmt
        run: deno fmt --check --ignore=wasm.js

      - name: Run deno lint
        run: deno lint --ignore=wasm.js

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run deno test
        run: deno test --allow-none
